// react/src/YXUIKit/im-kit-ui/src/chat/components/ChatCollectionList/CollectionItem.tsx
import React, { useMemo } from 'react'
import {
  CommonIcon,
  ParseSession,
  useStateContext,
  useTranslation,
} from '../../../common'
import {
  V2NIMCollection,
  V2NIMMessage,
} from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMMessageService'
import { Dropdown, Menu } from 'antd'
import { DeleteOutlined } from '@ant-design/icons'
import { formatDate, mergeActions } from '../../../utils'
import { MenuItem } from '../ChatMessageItem'
import { CollectionMenuItem } from '.'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'

export interface CollectionItemProps {
  collection: V2NIMCollection
  menus?: CollectionMenuItem[]
  onMenuClick: (options: {
    key: string
    collection: V2NIMCollection
    msg: V2NIMMessage
  }) => void
  renderItem?: (options: {
    collection: V2NIMCollection
    msg: V2NIMMessage
  }) => JSX.Element | null | undefined

  prefix?: string
  commonPrefix?: string
}

const CollectionItem: React.FC<CollectionItemProps> = ({
  collection,
  menus,
  onMenuClick,
  renderItem,
  prefix = 'chat',
  commonPrefix = 'common',
}) => {
  const { t } = useTranslation()
  const { nim } = useStateContext()

  const collectionData = useMemo(() => {
    let data

    try {
      data = JSON.parse(collection.collectionData || '{}')
    } catch (error) {
      //
    }

    return data
  }, [collection.collectionData])

  const msg = useMemo(() => {
    return nim.V2NIMMessageConverter.messageDeserialization(
      collectionData.message
    ) as V2NIMMessage
  }, [collectionData, nim.V2NIMMessageConverter])

  const _prefix = `${prefix}-collection-item`

  const menuItems = useMemo(() => {
    const defaultMenus: MenuItem[] = [
      {
        show:
          msg?.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_AUDIO
            ? 0
            : 1,
        key: 'forward',
        label: t('forwardText'),
        icon: <CommonIcon type="icon-zhuanfa" />,
      },
      {
        show: 1,
        label: t('deleteText'),
        key: 'delete',
        icon: <DeleteOutlined />,
      },
    ]

    const finalMenus = menus
      ? mergeActions(defaultMenus, menus, 'key')
      : defaultMenus

    return finalMenus.filter((item) => item.show)
  }, [menus, t, msg?.messageType])

  const handleMenuClick = ({ key }: { key: string }) => {
    onMenuClick({
      key,
      collection,
      msg,
    })
  }

  return (
    renderItem?.({ msg, collection }) ?? (
      <Dropdown
        trigger={['contextMenu']}
        overlay={<Menu onClick={handleMenuClick} items={menuItems} />}
        getPopupContainer={(triggerNode) => triggerNode}
        overlayClassName={`${_prefix}-dropdown`}
      >
        <div className={`${_prefix}-wrap`}>
          {msg && <ParseSession msg={msg} prefix={commonPrefix} />}
          <div className={`${_prefix}-info`}>
            <span>{collectionData.senderName}</span>
            <span>
              {formatDate(collection.updateTime || collection.createTime)}
            </span>
          </div>
        </div>
      </Dropdown>
    )
  )
}

export default CollectionItem

// vue3-demo/src/components/NEUIKit/Chat/collection/collection-item.vue
<template>
  <div class="collection-item-content">
    <div class="collection-item-content-top">
      <div class="collection-item-content-top-msg">
        <MessageItemContent :msg="msg" />
      </div>
      <div class="collection-item-content-top-icon">
        <Dropdown trigger="click">
          <div class="collection-item-more-btn">...</div>
          <template #overlay>
            <div class="collection-item-menu">
              <div
                v-for="item in menuItems"
                :key="item.key"
                class="collection-item-menu-item"
                @click="handleMenuClick(item.key)"
              >
                <Icon
                  v-if="item.icon"
                  :type="item.icon"
                  class="collection-item-menu-icon"
                />
                <span>{{ item.label }}</span>
              </div>
            </div>
          </template>
        </Dropdown>
      </div>
    </div>
    <div class="collection-item-info">
      <span>{{ collectionData?.senderName }}</span>
      <span>{{
        formatDate(collection.updateTime || collection.createTime)
      }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import Dropdown from "../message/message-dropdown.vue";
import Icon from "../../CommonComponents/Icon.vue";
import { t } from "../../utils/i18n";
import { formatDate } from "../../utils/date";
import type {
  V2NIMCollection,
  V2NIMMessage,
} from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMMessageService";
import MessageItemContent from "../message/message-item-content.vue";
import { nim } from "../../utils/init";
interface MenuItem {
  key: string;
  label: string;
  icon?: string;
  show?: number;
  onClick?: (params: {
    collection: V2NIMCollection;
    msg: V2NIMMessage;
  }) => void;
}

interface Props {
  collection: V2NIMCollection;
  menus?: MenuItem[];
}

const props = withDefaults(defineProps<Props>(), {});

// 定义事件
const emit = defineEmits<{
  "menu-click": [
    params: { key: string; collection: V2NIMCollection; msg: V2NIMMessage },
  ];
}>();

// 解析收藏数据
const collectionData = computed(() => {
  let data;
  try {
    data = JSON.parse(props.collection.collectionData || "{}");
  } catch (error) {
    console.log("collection.collectionData", error);
  }
  return data;
});

// 转换消息对象
const msg = computed(() => {
  return nim.V2NIMMessageConverter.messageDeserialization(
    collectionData.value?.message,
  ) as unknown as V2NIMMessage;
});

// 菜单项
const menuItems = computed(() => {
  const defaultMenus: MenuItem[] = [
    {
      show: msg.value?.messageType === 2 ? 0 : 1, // V2NIM_MESSAGE_TYPE_AUDIO
      key: "forward",
      label: t("forwardText"),
      icon: "icon-forward",
    },
    {
      show: 1,
      label: t("deleteText"),
      key: "delete",
      icon: "icon-shanchu",
    },
  ];

  return defaultMenus.filter((item) => item.show);
});

// 菜单点击处理
const handleMenuClick = (key: string) => {
  emit("menu-click", {
    key,
    collection: props.collection,
    //@ts-ignore
    msg: msg.value,
  });
};
</script>

<style scoped>
.collection-item-content {
  padding: 24px;
  margin: 20px 40px;
  background-color: #ffffff;
  border-radius: 10px;
  box-sizing: border-box;
}

.collection-item-content-top {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 8px;
}

.collection-item-content-top-msg {
  flex: 1;
  margin-right: 12px;
}

.collection-item-content-top-msg :deep(.audio-dur) {
  margin: 0px;
}

.collection-item-content-top-icon {
  flex-shrink: 0;
}

.collection-item-more-btn {
  font-size: 18px;
  font-weight: bold;
  color: #666;
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 4px;
}

.collection-item-more-btn:hover {
  background-color: #e9ecef;
}

.collection-item-info {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 12px;
  color: #999;
}

.collection-item-menu {
  background: white;
  border-radius: 6px;
  padding: 4px 0;
  min-width: 70px;
}

.collection-item-menu-item {
  display: flex;
  align-items: center;
  padding: 8px;
  cursor: pointer;
  font-size: 14px;
  color: #000;
}

.collection-item-menu-item:hover {
  background-color: #f0f0f0;
}

.collection-item-menu-icon {
  margin-right: 8px;
  font-size: 16px;
}

.parse-session {
  font-size: 14px;
  color: #333;
  line-height: 1.4;
}
</style>
