// react-demo/src/YXUIKit/im-kit-ui/src/conversation/components/pinAIItem.tsx
import { observer } from 'mobx-react'
import React, { FC } from 'react'
import {
  ComplexAvatarContainer,
  useStateContext,
  useTranslation,
} from '../../common'
import { V2NIMAIUser } from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMAIService'
import { message } from 'antd'
import { logger } from '../../utils'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'

export interface PinAIItemProps {
  aiUser: V2NIMAIUser

  prefix?: string
  commonPrefix?: string
}

export const PinAIItem: FC<PinAIItemProps> = observer(
  ({ aiUser, prefix = 'conversation', commonPrefix = 'common' }) => {
    const _prefix = `${prefix}-ai-item`

    const { store } = useStateContext()

    const { t } = useTranslation()

    const handleItemClick = () => {
      if (store.sdkOptions?.enableV2CloudConversation) {
        store.conversationStore
          ?.insertConversationActive(
            V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P,
            aiUser.accountId,
            true
          )
          .catch((err) => {
            message.error(t('aiConversationSelectFailed'))
            logger.error(err)
          })
      } else {
        store.localConversationStore
          ?.insertConversationActive(
            V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P,
            aiUser.accountId,
            true
          )
          .catch((err) => {
            message.error(t('aiConversationSelectFailed'))
            logger.error(err)
          })
      }
    }

    return (
      <div className={_prefix} onClick={() => handleItemClick()}>
        <ComplexAvatarContainer
          account={aiUser.accountId}
          prefix={commonPrefix}
          onMessageItemAvatarClick={() => handleItemClick()}
        />
        <span onClick={() => handleItemClick()} className={`${_prefix}-name`}>
          {store.uiStore.getAppellation({
            account: aiUser.accountId,
          })}
        </span>
      </div>
    )
  }
)

// vue3-demo/src/components/NEUIKit/Conversation/PinAIItem.vue
<template>
  <div class="conversation-ai-item" @click="handleItemClick">
    <Avatar size="36" :account="aiUser.accountId" />
    <Appellation
      class="conversation-ai-item-name"
      :account="aiUser.accountId"
      :fontSize="12"
    />
  </div>
</template>

<script lang="ts" setup>
import { showToast } from "../utils/toast";
import { t } from "../utils/i18n";
import { nim, store } from "../utils/init";
import Avatar from "../CommonComponents/Avatar.vue";
import Appellation from "../CommonComponents/Appellation.vue";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";

const props = defineProps<{
  aiUser: { accountId: string };
}>();

const handleItemClick = async () => {
  try {
    if (store?.sdkOptions?.enableV2CloudConversation) {
      await store?.conversationStore?.insertConversationActive(
        V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P,
        props.aiUser.accountId,
        true,
      );
    } else {
      await store?.localConversationStore?.insertConversationActive(
        V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P,
        props.aiUser.accountId,
        true,
      );
    }
  } catch (err) {
    showToast({ message: t("aiConversationSelectFailed"), type: "info" });
  }
};
</script>

<style scoped>
.conversation-ai-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  padding: 8px 4px;
  border-radius: 8px;
  min-width: 52px;
  max-width: 68px;
  transition: background-color 0.15s;
}

.conversation-ai-item:hover {
  background-color: #f3f5f7;
}

.conversation-ai-item-name {
  margin-top: 4px;
  max-width: 60px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  text-align: center;
  color: #333;
}
</style>
